---
title: "Datafest-CA"
author: "Ting Wang"
date: '2021-04-28'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dbplyr)
library(tidyverse)
library(readxl)
library(lme4)
library(gtsummary)
library(caret)
library(e1071)
library(randomForest)
library(ROCR)
```

##data
```{r,message=FALSE}
dataca <- read_csv("./Source Data/CA-Data/ca.csv")
attach(dataca)
head(dataca)
```
```{r}
useFENT <- na.omit(dataca$FENT_NMU) 
propFENT <- sum(useFENT == "1")/length(useFENT)

useBUP <- na.omit(dataca$BUP_NMU) 
propBUP <- sum(useBUP == "1")/length(useBUP)

useMETH <- na.omit(dataca$METH_NMU) 
propMETH <- sum(useMETH == "1")/length(useMETH)

useMORPH <- na.omit(dataca$MORPH_NMU) 
propMORPH <- sum(useMORPH == "1")/length(useMORPH)

useOXY <- na.omit(dataca$OXY_NMU) 
propOXY <- sum(useOXY == "1")/length(useOXY)

useOXYM <- na.omit(dataca$OXYM_NMU) 
propOXYM <- sum(useOXYM == "1")/length(useOXYM)

useTRAM <- na.omit(dataca$TRAM_NMU) 
propTRAM <- sum(useTRAM == "1")/length(useTRAM)

useTAP <- na.omit(dataca$TAP_NMU) 
propTAP <- sum(useTAP == "1")/length(useTAP)

useCOD <- na.omit(dataca$COD_NMU) 
propCOD <- sum(useCOD == "1")/length(useCOD)

useCOTC <- na.omit(dataca$COTC_NMU) 
propCOTC <- sum(useCOTC == "1")/length(useCOTC)

useHYD <- na.omit(dataca$HYD_NMU) 
propHYD <- sum(useHYD == "1")/length(useHYD)

useHYDM <- na.omit(dataca$HYDM_NMU) 
propHYDM <- sum(useHYDM == "1")/length(useHYDM)

useSUF <- na.omit(dataca$SUF_NMU) 
propSUF <- sum(useSUF == "1")/length(useSUF)

useSTIM <- na.omit(dataca$STIM_NMU) 
propSTIM <- sum(useSTIM == "1")/length(useSTIM)

useBENZ <- na.omit(dataca$BENZ_NMU) 
propBENZ <- sum(useBENZ == "1")/length(useBENZ)

useTHC <- na.omit(dataca$THC_NMU) 
propTHC <- sum(useTHC == "1")/length(useTHC)

prop <- c(propFENT, propBUP, propMETH, propMORPH, propOXY, propOXYM, propTRAM, propTAP, propCOD, propCOTC, propHYD, propHYDM, propSUF, propSTIM, propBENZ, propTHC)

drugs <- c('FENT', 'BUP','METH', 'MORPH', 'OXY', 'OXYM', 'TRAM', 'TAP', 'COD', 'COTC', 'HYD', 'HYDM', 'SUF', 'STIM', 'BENZ', 'THC')  

 
prop_misuse <- data.frame(drugs,prop)

plot_misuse<- ggplot(data=prop_misuse, aes(x=drugs, y=prop)) + 
  geom_bar(stat="identity", width=0.5) + 
  labs(title="Proportion of Misuse by Drug Type in Canada",
        x ="Drug Type", y = "Proportion of Misuse") + theme_classic() + scale_color_manual(values=c("chocolate2"))+
  scale_fill_manual(values=c("steelblue"))

plot_misuse


```

```{r}
dataca$FENT_NMU[is.na(dataca$FENT_NMU)] <- 0
dataca$BUP_NMU[is.na(dataca$BUP_NMU)] <- 0
dataca$METH_NMU[is.na(dataca$METH_NMU)] <- 0
dataca$MORPH_NMU[is.na(dataca$MORPH_NMU)] <- 0
dataca$OXY_NMU[is.na(dataca$OXY_NMU)] <- 0
dataca$OXYM_NMU[is.na(dataca$OXYM_NMU)] <- 0
dataca$TRAM_NMU[is.na(dataca$TRAM_NMU)] <- 0
dataca$TAP_NMU[is.na(dataca$TAP_NMU)] <- 0
dataca$COD_NMU[is.na(dataca$COD_NMU)] <- 0
dataca$COTC_NMU[is.na(dataca$COTC_NMU)] <- 0
dataca$HYD_NMU[is.na(dataca$HYD_NMU)] <- 0
dataca$HYDM_NMU[is.na(dataca$HYDM_NMU)] <- 0
dataca$SUF_NMU[is.na(dataca$SUF_NMU)] <- 0
dataca$STIM_NMU[is.na(dataca$STIM_NMU)] <- 0
dataca$BENZ_NMU[is.na(dataca$BENZ_NMU)] <- 0
dataca$THC_NMU[is.na(dataca$THC_NMU)] <- 0

dataca <- dataca %>%
  mutate(total_misuse =FENT_NMU + BUP_NMU + METH_NMU + MORPH_NMU + OXY_NMU + OXYM_NMU + TRAM_NMU + TAP_NMU + COD_NMU + COTC_NMU + HYD_NMU + HYDM_NMU + SUF_NMU + STIM_NMU +  BENZ_NMU + THC_NMU)
hist(dataca$total_misuse)
boxplot(dataca$total_misuse,main="Boxplot of Total Misuses in Canada")
summary(dataca$total_misuse)
```

##modelling
```{r}
dataca$DEM_AGE10<- as.factor(dataca$DEM_AGE10)
dataca$DEM_GENDER <- as.factor(dataca$DEM_GENDER)
dataca$DEM_ABOR <- as.factor(dataca$DEM_ABOR)
dataca$DEM_LOCATION <- as.factor(dataca$DEM_LOCATION)
dataca$DEM_MARITAL <- as.factor(dataca$DEM_MARITAL)
dataca$DEM_INCOME <- as.factor(dataca$DEM_INCOME)
dataca$DEM_EDU <- as.factor(dataca$DEM_EDU)
dataca$ALC_FREQ_USE <- as.factor(dataca$ALC_FREQ_USE)
dataca$TOB_FREQ_USE <- as.factor(dataca$TOB_FREQ_USE)
dataca$OTH_RX_DRUG_USE <- as.factor(dataca$OTH_RX_DRUG_USE)

model1 <- lm(total_misuse ~ DEM_GENDER + DEM_AGE10 + DEM_ABOR + DEM_LOCATION + DEM_MARITAL + DEM_INCOME + DEM_EDU + ALC_FREQ_USE + TOB_FREQ_USE + OTH_RX_DRUG_USE, data = dataca)
summary(model1)


#model1 <- glm(total_misuse ~ DEM_GENDER + DEM_AGE10 + DEM_ABOR + DEM_LOCATION + DEM_MARITAL + DEM_INCOME + DEM_EDU + ALC_FREQ_USE + TOB_FREQ_USE + OTH_RX_DRUG_USE, family=poisson, data = dataca)
#summary(model1)
#sig var include age, abor, location (all besides NB, Nunavut and Northwest), marital (common law and seperated), income (160,000 or more and refer not to say), edu (trade and uni below bachelor)

#male more misuse 
#higher age, less misuse 
#being abor, more misuse 
#locations are sig, baseline is New found land and labrador 
#married is the lowest misuse, other types increase misuse 
#higher income, less misuse 
#higher edu, generally less misuse, most misuse for University certificate or diploma below the bachelor's level
```

```{r}
#dataca$DEM_PREG[is.na(dataca$DEM_PREG)] <- 0
#dataca$DEM_HEALTH[is.na(dataca$DEM_HEALTH)] <- 0
#dataca$HEALTH_RX[is.na(dataca$HEALTH_RX)] <- 0

#dataca$DEM_PREG <- as.factor(dataca$DEM_PREG)
#dataca$DEM_HEALTH <- as.factor(dataca$DEM_HEALTH)
#dataca$HEALTH_RX <- as.factor(dataca$HEALTH_RX)

#dataca$PAIN_CHRONIC <- as.factor(dataca$PAIN_CHRONIC)
#dataca$PAIN_ACUTE <- as.factor(dataca$PAIN_ACUTE)

model2 <- lm(total_misuse ~ DEM_PREG + DEM_HEALTH + HEALTH_RX + HELP_SUB_USE + DRSHOP_NMU + DRSHOP_SELL + HPC_USE + HPC_SELL, data = dataca)
#model2 <- glm(total_misuse ~ DEM_PREG + DEM_HEALTH + HEALTH_RX + HELP_SUB_USE + DRSHOP_NMU + DRSHOP_SELL + HPC_USE + HPC_SELL, family=poisson, data = dataca)
summary(model2)
#only help_sub_use sig, it significantly increases misuses 
```

```{r}
model3 <- lm(total_misuse ~ PAIN_CHRONIC + PAIN_ACUTE + MENT_ANX + MENT_ADHD + MENT_AUT + MENT_BIP + MENT_BPD + MENT_DEP + MENT_EAT + MENT_OCD + MENT_PANIC + MENT_PPD + MENT_PTSD + MENT_SCH + MENT_OTH + MENT_NONE, data = dataca)
#model3 <- glm(total_misuse ~ PAIN_CHRONIC + PAIN_ACUTE + MENT_ANX + MENT_ADHD + MENT_AUT + MENT_BIP + MENT_BPD + MENT_DEP + MENT_EAT + MENT_OCD + MENT_PANIC + MENT_PPD + MENT_PTSD + MENT_SCH + MENT_OTH + MENT_NONE, family=poisson, data = dataca)
summary(model3)
```
##visualization
```{r,eval=FALSE}
dataca %>% 
  ggplot(aes(x=location, y=total_misuse, col=gender))+
  geom_point()+
  theme_light()

dataca %>% 
  ggplot(aes(x=DEM_AGE10, y=total_misuse, col=gender))+
  geom_point()+
  theme_light()

dataca %>% 
  ggplot(aes(x=edu, y=total_misuse, col=gender))+
  geom_point()+
  theme_light()

dataca %>% 
  ggplot(aes(x=income, y=total_misuse, col=gender))+
  geom_point()+
  theme_light()

dataca$DEM_GENDER[dataca$DEM_GENDER == 1] <- "Male"
dataca$DEM_GENDER[dataca$DEM_GENDER == 2] <- "Female"
dataca$total_misuse <- as.factor(dataca$total_misuse)

dataca%>%
  select(total_misuse,DEM_GENDER)%>%
  tbl_summary(by=DEM_GENDER)%>%
  modify_header(label ~ "**Variable**")

```


##random forest
```{r}
dataca <- dataca%>% mutate(has_misuse = ifelse(total_misuse >= 1, 1, 0))
dataca$has_misuse <- as.factor(dataca$has_misuse)

# 80% train 20% test
smp_size <- floor(0.8 * nrow(dataca))
#set seed
set.seed(1234)
train_ind <- sample(seq_len(nrow(dataca)), size = smp_size)

train <- dataca[train_ind, ]
test <- dataca[-train_ind, ]
```

```{r}
set.seed(1234)
rf_ca <-randomForest(has_misuse~ DEM_GENDER + DEM_AGE10 + DEM_ABOR + DEM_LOCATION + DEM_MARITAL + DEM_INCOME + DEM_EDU + ALC_FREQ_USE + TOB_FREQ_USE + OTH_RX_DRUG_USE + HELP_SUB_USE + PAIN_CHRONIC + PAIN_ACUTE + MENT_NONE,data=dataca, ntree=500) 

print(rf_ca)
importance(rf_ca)
varImpPlot(rf_ca)
```

```{r}
pred1=predict(rf_ca,type = "prob")
perf = prediction(pred1[,2], dataca$has_misuse)
# 1. Area under curve
auc = performance(perf, "auc")
#auc
# 2. True Positive and Negative Rate
pred3 = performance(perf, "tpr","fpr")
# 3. Plot the ROC curve
plot(pred3,main="ROC Curve for Random Forest for CA",col=2,lwd=2)
abline(a=0,b=1,lwd=2,lty=2,col="gray")

pred <- predict(rf_ca, newdata=test)
confusionMatrix(pred,test$has_misuse)
```

```{r,eval=FALSE}
trControl <- trainControl(method = "cv",
    number = 10,
    search = "grid")

rf_default <- train(has_misuse~ DEM_GENDER + DEM_AGE10 + DEM_ABOR + DEM_REGION + DEM_MARITAL + DEM_INCOME + DEM_EDU + ALC_FREQ_USE + TOB_FREQ_USE + OTH_RX_DRUG_USE + HELP_SUB_USE + PAIN_CHRONIC + PAIN_ACUTE + MENT_NONE,data=train,
    method = "rf",
    metric = "Accuracy",
    trControl = trControl)

prediction <-predict(rf_default, test)
confusionMatrix(prediction, test$has_misuse)
```





##see which people tend do use a specific drug 
```{r,eval=FALSE}
dataca %>% filter(FENT_NMU =="1")%>%
  ggplot(aes(x=DEM_AGE10,y=DEM_INCOME,col=as.factor(DEM_GENDER)))+
  geom_point()+
  facet_wrap(~DEM_REGION,nrow=3)+
  theme_light()


dataca %>% filter(FENT_NMU =="1")%>%
  ggplot(aes(x=DEM_AGE10,y=DEM_INCOME,col=as.factor(DEM_GENDER)))+
  geom_point()+
  facet_wrap(~DEM_REGION,nrow=3)+
  theme_light()

FentUser <- dataca %>% filter(FENT_NMU =="1")
hist(FentUser$DEM_AGE10)

par(mfrow=c(4,4))
hist((dataca %>% filter(FENT_NMU =="1"))$DEM_AGE10,main="FENT",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(BUP_NMU =="1"))$DEM_AGE10,main="BUP",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(METH_NMU =="1"))$DEM_AGE10,main="METH",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(MORPH_NMU =="1"))$DEM_AGE10,main="MORPH",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(OXY_NMU =="1"))$DEM_AGE10,main="OXY",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(OXYM_NMU =="1"))$DEM_AGE10,main="OXYM",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(TRAM_NMU =="1"))$DEM_AGE10,main="TRAM",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(TAP_NMU =="1"))$DEM_AGE10,main="TAP",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(COD_NMU =="1"))$DEM_AGE10,main="COD",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(COTC_NMU =="1"))$DEM_AGE10,main="COTC",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(HYD_NMU =="1"))$DEM_AGE10,main="HYD",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(HYDM_NMU =="1"))$DEM_AGE10,main="HYDM",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(SUF_NMU =="1"))$DEM_AGE10,main="SUF",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(STIM_NMU =="1"))$DEM_AGE10,main="STIM",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(BENZ_NMU =="1"))$DEM_AGE10,main="BENZ",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(THC_NMU =="1"))$DEM_AGE10,main="THC",xlab="Age",ylim=c(0,80))


```


## which type of people are more likely to misuse which drugs 
```{r}
dataca <- dataca %>%
  mutate(misuse_pr=ifelse(FENT_NMU == "1" | BUP_NMU == "1"| METH_NMU == "1"| MORPH_NMU == "1"| OXY_NMU == "1"| OXYM_NMU == "1"| TRAM_NMU == "1"| TAP_NMU == "1"| HYD_NMU == "1"| HYDM_NMU == "1"| SUF_NMU == "1",1,0)) %>%
  mutate(misuse_co=ifelse(COD_NMU == "1"| COTC_NMU == "1",1,0))%>%
  mutate(misuse_others=ifelse(STIM_NMU == "1" | BENZ_NMU == "1"| THC_NMU == "1",1,0))

dataca$misuse_pr <- as.factor(dataca$misuse_pr)
dataca$misuse_co <- as.factor(dataca$misuse_co)
dataca$misuse_others <- as.factor(dataca$misuse_others)

model4 <- glm(misuse_pr ~ DEM_GENDER + DEM_AGE10 + DEM_ABOR + DEM_EDU + DEM_LOCATION +DEM_INCOME, data=dataca,family="binomial")
summary(model4)

model5 <- glm(misuse_co ~ DEM_GENDER + DEM_AGE10 + DEM_ABOR + DEM_EDU + DEM_LOCATION +DEM_INCOME, data=dataca,family="binomial")
summary(model5)

model6 <- glm(misuse_others ~ DEM_GENDER + DEM_AGE10 + DEM_ABOR + DEM_EDU + DEM_LOCATION + DEM_INCOME, data=dataca,family="binomial")
summary(model6)

```
```{r}

dataca <- dataca %>%
  mutate(use_pr=ifelse(FENT_USE == "1" | BUP_USE == "1"| METH_USE == "1"| MORPH_USE == "1"| OXY_USE == "1"| OXYM_USE == "1"| TRAM_USE == "1"| TAP_USE == "1"| HYD_USE == "1"| HYDM_USE == "1"| SUF_USE == "1",1,0)) %>%
  mutate(use_co=ifelse(COD_USE == "1",1,0))%>%
  mutate(use_others=ifelse(STIM_USE == "1" | BENZ_USE == "1"| THC_USE == "1",1,0))


proppr <- sum(dataca$misuse_pr == "1")/sum(dataca$use_pr == "1")
propco <- sum(dataca$misuse_co == "1")/sum(dataca$use_co == "1")
propother <- sum(dataca$misuse_others == "1")/sum(dataca$use_others == "1")


newprop <- c(proppr, propco, propother)
drugtype <- c('Pain Reliever', 'Codeine', 'Others')

 
prop_type <- data.frame(drugtype,newprop)

plot_type <- ggplot(data=prop_type, aes(x=drugtype, y=newprop)) + 
  geom_bar(stat="identity", width=0.5) + 
  labs(title="Proportion of Misuse by Three Drug Types",
        x ="Drug Type", y = "Proportion of Misuse") + theme_classic() + scale_color_manual(values=c("chocolate2"))+
  scale_fill_manual(values=c("steelblue"))

plot_type
```





##which drugs are often misused together 
```{r,message=FLASE}
#install.packages("Hmisc")
#install.packages("corrplot")
library("Hmisc")
library(corrplot)
misuse<- dataca %>% select(FENT_NMU, BUP_NMU, METH_NMU, MORPH_NMU, OXY_NMU, OXYM_NMU, TRAM_NMU, TAP_NMU, COD_NMU, COTC_NMU, HYD_NMU, HYDM_NMU, SUF_NMU, STIM_NMU, BENZ_NMU, THC_NMU)


res <- cor(misuse)
round(res, 3)

corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

```

```{r,eval=FALSE}
drugs <- c('FENT', 'BUP','METH', 'MORPH', 'OXY', 'OXYM', 'TRAM', 'TAP', 'COD', 'COTC', 'HYD', 'HYDM', 'SUF', 'STIM', 'BENZ', 'THC')  
propmisuse_geo <- dataca %>% group_by(DEM_LOCATION) %>% summarise(FENT = sum(na.omit(FENT_NMU))/length(na.omit(FENT_NMU)), BUP = sum(na.omit(BUP_NMU))/length(na.omit(BUP_NMU)), METH = sum(na.omit(METH_NMU))/length(na.omit(METH_NMU)), MORPH = sum(na.omit(MORPH_NMU))/length(na.omit(MORPH_NMU)), OXY = sum(na.omit(OXY_NMU))/length(na.omit(OXY_NMU)), OXYM = sum(na.omit(OXYM_NMU))/length(na.omit(OXYM_NMU)), TRAM = sum(na.omit(TRAM_NMU))/length(na.omit(TRAM_NMU)), TAP = sum(na.omit(TAP_NMU))/length(na.omit(TAP_NMU)), COD = sum(na.omit(COD_NMU))/length(na.omit(COD_NMU)), COTC = sum(na.omit(COTC_NMU))/length(na.omit(COTC_NMU)), HYD = sum(na.omit(HYD_NMU))/length(na.omit(HYD_NMU)),HYDM = sum(na.omit(HYDM_NMU))/length(na.omit(HYDM_NMU)),SUF = sum(na.omit(SUF_NMU))/length(na.omit(SUF_NMU)),STIM = sum(na.omit(STIM_NMU))/length(na.omit(STIM_NMU)),BENZ = sum(na.omit(BENZ_NMU))/length(na.omit(BENZ_NMU)),THC = sum(na.omit(THC_NMU))/length(na.omit(THC_NMU)))
propmisuse_geo$FENT[is.na(propmisuse_geo$FENT)] <- 0
propmisuse_geo$BUP[is.na(propmisuse_geo$BUP)] <- 0
propmisuse_geo$METH[is.na(propmisuse_geo$METH)] <- 0
propmisuse_geo$MORPH[is.na(propmisuse_geo$MORPH)] <- 0
propmisuse_geo$OXY[is.na(propmisuse_geo$OXY)] <- 0
propmisuse_geo$OXYM[is.na(propmisuse_geo$OXYM)] <- 0
propmisuse_geo$TRAM[is.na(propmisuse_geo$TRAM)] <- 0
propmisuse_geo$TAP[is.na(propmisuse_geo$TAP)] <- 0
propmisuse_geo$COD[is.na(propmisuse_geo$COD)] <- 0
propmisuse_geo$COTC[is.na(propmisuse_geo$COTC)] <- 0
propmisuse_geo$HYD[is.na(propmisuse_geo$HYD)] <- 0
propmisuse_geo$HYDM[is.na(propmisuse_geo$HYDM)] <- 0
propmisuse_geo$SUF[is.na(propmisuse_geo$SUF)] <- 0
propmisuse_geo$STIM[is.na(propmisuse_geo$STIM)] <- 0
propmisuse_geo$BENZ[is.na(propmisuse_geo$BENZ)] <- 0
propmisuse_geo$THC[is.na(propmisuse_geo$THC)] <- 0
propmisuse_geo
```
```{r,eval=FALSE}
prop_geo <- dataca %>% group_by(DEM_LOCATION) %>% summarise(prop=sum(total_misuse)/length(total_misuse))
#test <- dataca %>% filter(DEM_LOCATION=="12")

prop_geo$csi <- c(63.51,66.26,45.86, 68.74,57.82, 56.34,119.01,143.1,112,87.23,300.43,309.36)
plot(prop_geo$prop,prop_geo$csi)
```



```{r}
#from statsCan, Dec2016
dataca <-dataca%>%
  mutate(healthcpi=case_when(DEM_LOCATION=="1" ~ 114.7,
                             DEM_LOCATION=="2" ~ 116.8,
                             DEM_LOCATION=="3" ~ 116,
                             DEM_LOCATION=="4" ~ 113.8,
                             DEM_LOCATION=="5" ~ 123.6,
                             DEM_LOCATION=="6" ~ 126.6,
                             DEM_LOCATION=="7" ~ 118.1,
                             DEM_LOCATION=="8" ~ 119.2,
                             DEM_LOCATION=="9" ~ 142.6,
                             DEM_LOCATION=="10" ~ 119.8,
                             DEM_LOCATION=="11" ~ 125.2,
                             DEM_LOCATION=="12" ~ 125.2,
                             DEM_LOCATION=="13" ~ 117.6))

#from statsCan, 2017
dataca <-dataca%>%
  mutate(csi=case_when(DEM_LOCATION=="1" ~ 63.51,
                       DEM_LOCATION=="2" ~ 66.26,
                       DEM_LOCATION=="3" ~ 45.86,
                       DEM_LOCATION=="4" ~ 68.74,
                       DEM_LOCATION=="5" ~ 57.82,
                       DEM_LOCATION=="6" ~ 56.34,
                       DEM_LOCATION=="7" ~ 119.01,
                       DEM_LOCATION=="8" ~ 143.1,
                       DEM_LOCATION=="9" ~ 112,
                       DEM_LOCATION=="10" ~ 87.23,
                       DEM_LOCATION=="11" ~ 183.56,
                       DEM_LOCATION=="12" ~ 300.43,
                       DEM_LOCATION=="13" ~ 309.36))

#from statsCan, 2017
dataca <-dataca%>%
  mutate(healthcare_pctg=case_when(DEM_LOCATION=="1" ~ 87,
                       DEM_LOCATION=="2" ~ 86.2,
                       DEM_LOCATION=="3" ~ 82.4,
                       DEM_LOCATION=="4" ~ 91.9,
                       DEM_LOCATION=="5" ~ 78.5,
                       DEM_LOCATION=="6" ~ 90.1,
                       DEM_LOCATION=="7" ~ 83.9,
                       DEM_LOCATION=="8" ~ 81.4,
                       DEM_LOCATION=="9" ~ 83.7,
                       DEM_LOCATION=="10" ~ 82,
                       DEM_LOCATION=="11" ~ 78.8,
                       DEM_LOCATION=="12" ~ 13.9,
                       DEM_LOCATION=="13" ~ 37.3))
                            
model9<-glm(has_misuse~DEM_AGE10+DEM_GENDER+DEM_EDU+ DEM_ABOR+ DEM_INCOME + healthcpi + csi +healthcare_pctg,family="binomial",data=dataca)
summary(model9)
  
  
         
         
```



```{r,eval=FALSE}
dataca <- dataca%>% mutate(has_misuse = ifelse(total_misuse >= 1, 1, 0))
geo <- dataca %>%
  group_by(DEM_LOCATION)%>%
  summarise(prop_misuse = sum(has_misuse)/n())

csi <- c(63.51, 66.26, 45.86, 68.74, 57.82, 56.34, 119.01, 143.1, 112, 87.23)

cpi <- c(114.7, 116.8, 116, 113.8, 123.6, 126.6, 118.1, 119.2, 142.6,119.8)

healthp<-c(87,86.2,82.4,91.9,78.5,90.1,83.9,81.4,83.7,82)

#plot(cpi,geo$prop_misuse)
```





