---
title: "ASA Data Visualization"
author: "wr9450"
date: "28/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dbplyr)
library(tidyverse)
library(readxl)
library(cowplot)
library(viridis)
library(gtsummary)
library(plotly)
library(gplots)
library(RColorBrewer)
library(heatmaply)
library(ggthemes)
library(ggridges)

```

```{r,message=FALSE}
dataca <- read_csv("../Data Cleaning/CA_Clean.csv")
datade <- read_csv("../Data Cleaning/DE_Clean.csv")
datauk <- read_csv("../Data Cleaning/UK_Clean.csv")
dataus18 <- read_csv("../Data Cleaning/US18_Clean.csv")
dataca_totalmisuse <- read_csv("../Data Cleaning/CA_total_misuse.csv")

attach(dataca)
dataca
```

## Drug Misuse Visualization

```{r}
useFENT <- na.omit(dataca$FENT_NMU) 
propFENT <- sum(useFENT == "1")/length(useFENT)

useBUP <- na.omit(dataca$BUP_NMU) 
propBUP <- sum(useBUP == "1")/length(useBUP)

useMETH <- na.omit(dataca$METH_NMU) 
propMETH <- sum(useMETH == "1")/length(useMETH)

useMORPH <- na.omit(dataca$MORPH_NMU) 
propMORPH <- sum(useMORPH == "1")/length(useMORPH)

useOXY <- na.omit(dataca$OXY_NMU) 
propOXY <- sum(useOXY == "1")/length(useOXY)

useOXYM <- na.omit(dataca$OXYM_NMU) 
propOXYM <- sum(useOXYM == "1")/length(useOXYM)

useTRAM <- na.omit(dataca$TRAM_NMU) 
propTRAM <- sum(useTRAM == "1")/length(useTRAM)

useTAP <- na.omit(dataca$TAP_NMU) 
propTAP <- sum(useTAP == "1")/length(useTAP)

useCOD <- na.omit(dataca$COD_NMU) 
propCOD <- sum(useCOD == "1")/length(useCOD)

useCOTC <- na.omit(dataca$COTC_NMU) 
propCOTC <- sum(useCOTC == "1")/length(useCOTC)

useHYD <- na.omit(dataca$HYD_NMU) 
propHYD <- sum(useHYD == "1")/length(useHYD)

useHYDM <- na.omit(dataca$HYDM_NMU) 
propHYDM <- sum(useHYDM == "1")/length(useHYDM)

useSUF <- na.omit(dataca$SUF_NMU) 
propSUF <- sum(useSUF == "1")/length(useSUF)

useSTIM <- na.omit(dataca$STIM_NMU) 
propSTIM <- sum(useSTIM == "1")/length(useSTIM)

useBENZ <- na.omit(dataca$BENZ_NMU) 
propBENZ <- sum(useBENZ == "1")/length(useBENZ)

useTHC <- na.omit(dataca$THC_NMU) 
propTHC <- sum(useTHC == "1")/length(useTHC)

prop <- c(propFENT, propBUP, propMETH, propMORPH, propOXY, propOXYM, propTRAM, propTAP, propCOD, propCOTC, propHYD, propHYDM, propSUF, propSTIM, propBENZ, propTHC)

drugs <- c('FENT', 'BUP','METH', 'MORPH', 'OXY', 'OXYM', 'TRAM', 'TAP', 'COD', 'COTC', 'HYD', 'HYDM', 'SUF', 'STIM', 'BENZ', 'THC')  
cate <- c('')

 
prop_misuse <- data.frame(drugs,prop)

plot_misuse<- ggplot(data=prop_misuse, aes(x=drugs, y=prop)) + 
  geom_bar(stat="identity", width=0.5) + 
  labs(title="Proportion of Misuse by Drug Type in Canada",
        x ="Drug Type", y = "Proportion of Misuse") + theme_classic() + scale_color_manual(values=c("chocolate2"))+
  scale_fill_manual(values=c("steelblue"))

plot_misuse
ggsave("Proportion of misuse by drug type in Canada.png", plot_misuse)
```


```{r}
# Proportion of Misuse by Drug Type by province in Canada
drugs <- c('FENT', 'BUP','METH', 'MORPH', 'OXY', 'OXYM', 'TRAM', 'TAP', 'COD', 'COTC', 'HYD', 'HYDM', 'SUF', 'STIM', 'BENZ', 'THC')  

propmisuse_geo <- dataca %>% group_by(DEM_LOCATION) %>% summarise(FENT = sum(na.omit(FENT_NMU))/length(na.omit(FENT_NMU)), BUP = sum(na.omit(BUP_NMU))/length(na.omit(BUP_NMU)), METH = sum(na.omit(METH_NMU))/length(na.omit(METH_NMU)), MORPH = sum(na.omit(MORPH_NMU))/length(na.omit(MORPH_NMU)), OXY = sum(na.omit(OXY_NMU))/length(na.omit(OXY_NMU)), OXYM = sum(na.omit(OXYM_NMU))/length(na.omit(OXYM_NMU)), TRAM = sum(na.omit(TRAM_NMU))/length(na.omit(TRAM_NMU)), TAP = sum(na.omit(TAP_NMU))/length(na.omit(TAP_NMU)), COD = sum(na.omit(COD_NMU))/length(na.omit(COD_NMU)), COTC = sum(na.omit(COTC_NMU))/length(na.omit(COTC_NMU)), HYD = sum(na.omit(HYD_NMU))/length(na.omit(HYD_NMU)),HYDM = sum(na.omit(HYDM_NMU))/length(na.omit(HYDM_NMU)),SUF = sum(na.omit(SUF_NMU))/length(na.omit(SUF_NMU)),STIM = sum(na.omit(STIM_NMU))/length(na.omit(STIM_NMU)),BENZ = sum(na.omit(BENZ_NMU))/length(na.omit(BENZ_NMU)),THC = sum(na.omit(THC_NMU))/length(na.omit(THC_NMU)))
propmisuse_geo$FENT[is.na(propmisuse_geo$FENT)] <- 0
propmisuse_geo$BUP[is.na(propmisuse_geo$BUP)] <- 0
propmisuse_geo$METH[is.na(propmisuse_geo$METH)] <- 0
propmisuse_geo$MORPH[is.na(propmisuse_geo$MORPH)] <- 0
propmisuse_geo$OXY[is.na(propmisuse_geo$OXY)] <- 0
propmisuse_geo$OXYM[is.na(propmisuse_geo$OXYM)] <- 0
propmisuse_geo$TRAM[is.na(propmisuse_geo$TRAM)] <- 0
propmisuse_geo$TAP[is.na(propmisuse_geo$TAP)] <- 0
propmisuse_geo$COD[is.na(propmisuse_geo$COD)] <- 0
propmisuse_geo$COTC[is.na(propmisuse_geo$COTC)] <- 0
propmisuse_geo$HYD[is.na(propmisuse_geo$HYD)] <- 0
propmisuse_geo$HYDM[is.na(propmisuse_geo$HYDM)] <- 0
propmisuse_geo$SUF[is.na(propmisuse_geo$SUF)] <- 0
propmisuse_geo$STIM[is.na(propmisuse_geo$STIM)] <- 0
propmisuse_geo$BENZ[is.na(propmisuse_geo$BENZ)] <- 0
propmisuse_geo$THC[is.na(propmisuse_geo$THC)] <- 0
propmisuse_geo

# C(FENT_MUR, BUP_MUR, METH_MUR, MORPH_MUR, OXY_MUR, OXYM_MUR, TRAM_MUR, TAP_MUR, COD_MUR, COTC_MUR, HYD_MUR, HYDM_MUR, SUF_MUR, STIM_MUR, BENZ_MUR, THC_MUR)

rnames <- propmisuse_geo$DEM_LOCATION           
mat_data <- data.matrix(propmisuse_geo[,2:ncol(propmisuse_geo)]) 
rownames(mat_data) <- rnames  

prov <- heatmaply(mat_data,
          xlab = "Drugs",
          ylab = "Provinces",
          main = "Proportion of Misuse by Drug Type in Canada by Province",
          scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
    low = "steelblue", 
    high = "chocolate2", 
    midpoint = 0.5, 
    limits = c(0, 1)
  ))
htmlwidgets::saveWidget(prov, "province.html")

```




```{r}
hist(dataca_totalmisuse$total_misuse)
boxplot(dataca_totalmisuse$total_misuse)
```


```{r}
locationf <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female")  %>%
  ggplot(aes(x=as.factor(DEM_LOCATION), y=total_misuse))+
  geom_point(alpha = 0.1, size = 7, color = "chocolate2")+
  xlab("current location") + ylim(0, 15) +
  theme_light() +ggtitle("Total Misuse by location for Female")

locationm <- dataca_totalmisuse %>% filter(DEM_GENDER == "Male")  %>%
  ggplot(aes(x=as.factor(DEM_LOCATION), y=total_misuse))+
  geom_point(alpha = 0.1, size = 7, color = "steelblue")+ 
  xlab("current location") +
  theme_light()+ggtitle("Total Misuse by location for Male")
locationgender <- plot_grid(locationf, locationm)
locationgender

locationmisuse <- dataca_totalmisuse %>% 
  ggplot(aes(x=DEM_LOCATION, y=total_misuse))+
  geom_point(alpha = 0.5, size = 7, colour = "chocolate")+
  theme_light()
ggplotly(locationmisuse)

agef <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female") %>%
  ggplot(aes(x=as.factor(DEM_AGE10), y=total_misuse))+
  geom_point(alpha = 0.08, size = 7, color = "chocolate2")+ 
  ggtitle("Total Misuse by age for Female") + ylim(0, 15)+ xlab("Age Group") +
  theme_light()
agem <- dataca_totalmisuse %>% filter(DEM_GENDER == "Male") %>%
  ggplot(aes(x=as.factor(DEM_AGE10), y=total_misuse))+
  geom_point(alpha = 0.08, size = 7, color = "steelblue")+ 
  ggtitle("Total Misuse by age for Male") + xlab("Age Group") +
  theme_light()
agegender <- plot_grid(agef, agem)
agegender

eduf<- dataca_totalmisuse %>% filter(DEM_GENDER == "Female") %>%
  ggplot(aes(x=DEM_EDU, y=total_misuse))+
  geom_point(alpha = 0.1, size = 7, color = "chocolate2")+ ylim(0, 15) +
  ggtitle("Total Misuse by Education Level for Female") + xlab("Education Level")+
  theme_light()
edum<- dataca_totalmisuse %>% filter(DEM_GENDER == "Male") %>%
  ggplot(aes(x=DEM_EDU, y=total_misuse))+
  geom_point(alpha = 0.1, size = 7, color = "steelblue")+ ylim(0, 15) +
  ggtitle("Total Misuse by Education Level for Male") + xlab("Education Level")+
  theme_light()
edugender <- plot_grid(eduf, edum)
edugender

incomef <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female") %>%
  ggplot(aes(x=DEM_INCOME, y=total_misuse))+ ylim(0, 15) +
  geom_point(alpha = 0.1, size = 7, color = "chocolate2")+
  ggtitle("Total Misuse by income for Female") + xlab("Income")+
  theme_light()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))
incomem <- dataca_totalmisuse %>% filter(DEM_GENDER == "Male") %>%
  ggplot(aes(x=DEM_INCOME, y=total_misuse))+ ylim(0, 15) +
  geom_point(alpha = 0.1, size = 7, color = "steelblue")+
  ggtitle("Total Misuse by income for Male") + xlab("Income")+
  theme_light()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))
incomegender <- plot_grid(incomef, incomem)
incomegender

ggsave("Total Misuse by location by gender.png", locationgender)
ggsave("Total Misuse by location.png", locationmisuse)
ggsave("Total Misuse by Age by Gender.png", agegender)
ggsave("Total Misuse by Education Level by Gender.png", edugender)
ggsave("Total Misuse by Income Level by Gender.png", incomegender)
```

```{r}
locationf <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female")  %>%
  ggplot(aes(x=as.factor(DEM_LOCATION), y=total_misuse))+
  geom_count(color = "chocolate2", alpha = 0.9)+
  xlab("current location") + ylim(0, 15) + scale_size_area(max_size = 8)+
  theme_light() +ggtitle("Total Misuse by location for Female")

locationm <- dataca_totalmisuse %>% filter(DEM_GENDER == "Male")  %>%
  ggplot(aes(x=as.factor(DEM_LOCATION), y=total_misuse))+
  geom_count(color = "steelblue", alpha = 0.9)+ 
  xlab("current location") + scale_size_area(max_size = 8)+
  theme_light()+ggtitle("Total Misuse by location for Male")
locationgender <- plot_grid(locationf, locationm)
locationgender
ggsave("Total Misuse by location by gender2.png", locationgender)

incomef <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female") %>%
  ggplot(aes(x=DEM_INCOME, y=total_misuse))+ ylim(0, 15) +
  geom_count(color = "chocolate2")+scale_size_area(max_size = 8)+
  ggtitle("Total Misuse by income for Female") + xlab("Income")+
  theme_light()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))
incomem <- dataca_totalmisuse %>% filter(DEM_GENDER == "Male") %>%
  ggplot(aes(x=DEM_INCOME, y=total_misuse))+ ylim(0, 15) +
  geom_count(color = "steelblue")+scale_size_area(max_size = 8)+
  ggtitle("Total Misuse by income for Male") + xlab("Income")+
  theme_light()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))
incomegender <- plot_grid(incomef, incomem)
incomegender
ggsave("Total Misuse by Income Level by Gender2.png", incomegender)
```

```{r}
dataca_totalmisuse$has_misuse

incomef <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female") %>%
  ggplot(aes(x=DEM_INCOME, y=has_misuse))+ ylim(0, 15) +
  geom_count(color = "chocolate2")+scale_size_area(max_size = 8)+
  ggtitle("Total Misuse by income for Female") + xlab("Income")+
  theme_light()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))

dataca_totalmisuse %>%
  ggplot() + geom_bar(aes(x=DEM_INCOME, fill=DEM_GENDER), color="#e9ecef", alpha=0.6, position = 'identity') +scale_fill_manual(values=c("chocolate2", "steelblue")) + geom_line(data = dat_misuse, aes(x= DEM_INCOME, y = misuse), size = 1.5,  group = 1) + theme_light() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(fill="") + scale_y_continuous(sec.axis = sec_axis(~./3, name = "Number of people who has misused drugs")) 

dataca_totalmisuse$DEM_INCOME <- factor(dataca_totalmisuse$DEM_INCOME, levels = c("<20,000", "20,000-39,999", "40,000-59,999", "60,000-79,999", "80,000-99,999", "100,000-119,999", "120,000-139,999", "140,000-159,999",">160,000"))

level_order <- c("<20,000", "20,000-39,999", "40,000-59,999", "60,000-79,999", "80,000-99,999", "100,000-119,999", "120,000-139,999", "140,000-159,999",">160,000")


dataca_totalmisuse %>%filter(DEM_INCOME != "prefer not say") %>%
  ggplot() + geom_bar(aes(x=factor(DEM_INCOME, level = level_order), fill=DEM_GENDER), position = position_dodge(), alpha=0.6) +scale_fill_manual(values=c("chocolate2", "steelblue")) + geom_line(data = dat_misuse, aes(x= DEM_INCOME, y = misuse), size = 1.5,  group = 1) + theme_light() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(fill="") + scale_y_continuous(sec.axis = sec_axis(~./3, name = "Number of people who has misused drugs")) + ggtitle("Number of people in each income group vs. \nNumber of people who has misused drugs") + ylab("Number of people in each income group by gender")

 

dat_misuse <- dataca_totalmisuse %>% group_by(DEM_INCOME) %>% summarise(misuse = sum(has_misuse))

dat_misuse %>%
  ggplot()+ geom_line(aes(x= DEM_INCOME, y = misuse), group = 1)
incomef
```


```{r}
#Pregnancy
total_preg <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female") %>%
  ggplot(aes(x=DEM_PREG, y=total_misuse))+ ylim(0, 15) +
  geom_count(color = "chocolate2")+scale_size_area(max_size = 8)+
  ggtitle("Total Misuse by Pregnancy for Female") + xlab("Pregnancy")+
  theme_light()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))

total_premonth <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female") %>%
  ggplot(aes(x=DEM_PREGMNTH, y=total_misuse))+ ylim(0, 15) +
  geom_count(color = "chocolate2")+scale_size_area(max_size = 8)+
  ggtitle("Total Misuse by pregnancy months for Female") + xlab("Pregnancy Month")+
  theme_light()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("Total Misuse by Income Level by pregnancy.png", total_preg)
ggsave("Total Misuse by Income Level by pregnancy month.png", total_premonth)
```

```{r}
maritalf <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female")  %>%
  ggplot(aes(x=DEM_MARITAL, y=total_misuse))+
  geom_count(color = "chocolate2", alpha = 0.9)+
  xlab("Marital Status") + ylim(0, 15) + scale_size_area(max_size = 8)+
  theme_light() +theme(axis.text.x = element_text(angle = 45, hjust = 1))+ggtitle("Total Misuse by Marital Status for Female")

maritalm <- dataca_totalmisuse %>% filter(DEM_GENDER == "Male")  %>%
  ggplot(aes(x=DEM_MARITAL, y=total_misuse))+
  geom_count(color = "steelblue", alpha = 0.9)+ 
  xlab("Marital Status") + scale_size_area(max_size = 8)+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme_light()+theme(axis.text.x = element_text(angle = 45, hjust = 1))+ggtitle("Total Misuse by Marital Status for Male")
maritalgender <- plot_grid(maritalf, maritalm)
maritalgender
```


```{r}
totgenderf <- dataca_totalmisuse %>% filter(DEM_GENDER == "Female") %>% ggplot(aes(x = total_misuse)) + geom_histogram(alpha =0.4, position = "identity", binwidth = 1) + scale_fill_manual(values = "chocolate2") + scale_color_manual(values ="chocolate2") 
#totgenderf <- ggplotly(totgenderf)

totgenderm <-dataca_totalmisuse %>% filter(DEM_GENDER == "Male") %>% ggplot(aes(x = total_misuse)) + geom_histogram(alpha =0.4, position = "identity", binwidth = 1) + scale_fill_manual(values = "chocolate2") + scale_color_manual(values ="chocolate2") 
#totgenderm <- ggplotly(totgenderm)
totgender <- plot_grid(totgenderf, totgenderm)
totgender

totgender<- dataca_totalmisuse %>% ggplot(aes(total_misuse,colour = DEM_GENDER)) + xlim(c(0, 16))+ theme_minimal_hgrid() + 
  geom_freqpoly(binwidth = 1)
l <- ggplotly(totgender)
htmlwidgets::saveWidget(l, "index.html")
```


```{r}
# Proportion of Misuse by Drug Type by age in Canada
propmisuse_age <- dataca %>% group_by(DEM_AGE10) %>% summarise(FENT = sum(na.omit(FENT_NMU))/length(na.omit(FENT_NMU)), BUP = sum(na.omit(BUP_NMU))/length(na.omit(BUP_NMU)), METH = sum(na.omit(METH_NMU))/length(na.omit(METH_NMU)), MORPH = sum(na.omit(MORPH_NMU))/length(na.omit(MORPH_NMU)), OXY = sum(na.omit(OXY_NMU))/length(na.omit(OXY_NMU)), OXYM = sum(na.omit(OXYM_NMU))/length(na.omit(OXYM_NMU)), TRAM = sum(na.omit(TRAM_NMU))/length(na.omit(TRAM_NMU)), TAP = sum(na.omit(TAP_NMU))/length(na.omit(TAP_NMU)), COD = sum(na.omit(COD_NMU))/length(na.omit(COD_NMU)), COTC = sum(na.omit(COTC_NMU))/length(na.omit(COTC_NMU)), HYD = sum(na.omit(HYD_NMU))/length(na.omit(HYD_NMU)),HYDM = sum(na.omit(HYDM_NMU))/length(na.omit(HYDM_NMU)),SUF = sum(na.omit(SUF_NMU))/length(na.omit(SUF_NMU)),STIM = sum(na.omit(STIM_NMU))/length(na.omit(STIM_NMU)),BENZ = sum(na.omit(BENZ_NMU))/length(na.omit(BENZ_NMU)),THC = sum(na.omit(THC_NMU))/length(na.omit(THC_NMU)))
propmisuse_age$FENT[is.na(propmisuse_age$FENT)] <- 0
propmisuse_age$BUP[is.na(propmisuse_age$BUP)] <- 0
propmisuse_age$METH[is.na(propmisuse_age$METH)] <- 0
propmisuse_age$MORPH[is.na(propmisuse_age$MORPH)] <- 0
propmisuse_age$OXY[is.na(propmisuse_age$OXY)] <- 0
propmisuse_age$OXYM[is.na(propmisuse_age$OXYM)] <- 0
propmisuse_age$TRAM[is.na(propmisuse_age$TRAM)] <- 0
propmisuse_age$TAP[is.na(propmisuse_age$TAP)] <- 0
propmisuse_age$COD[is.na(propmisuse_age$COD)] <- 0
propmisuse_age$COTC[is.na(propmisuse_age$COTC)] <- 0
propmisuse_age$HYD[is.na(propmisuse_age$HYD)] <- 0
propmisuse_age$HYDM[is.na(propmisuse_age$HYDM)] <- 0
propmisuse_age$SUF[is.na(propmisuse_age$SUF)] <- 0
propmisuse_age$STIM[is.na(propmisuse_age$STIM)] <- 0
propmisuse_age$BENZ[is.na(propmisuse_age$BENZ)] <- 0
propmisuse_age$THC[is.na(propmisuse_age$THC)] <- 0
propmisuse_age


rnames_age <- propmisuse_age$DEM_AGE10           
mat_data_age <- data.matrix(propmisuse_age[,2:ncol(propmisuse_age)]) 
rownames(mat_data_age) <- rnames_age

heatmaply(mat_data_age,
          xlab = "Drugs",
          ylab = "Age",
          main = "Drug misuse rates for each age by type of drugs",
          scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
    low = "steelblue", 
    high = "chocolate2", 
    midpoint = 0.5, 
    limits = c(0, 1)
  ))

```

```{r, include=FALSE}
propmisuse_marital <- dataca %>% group_by(DEM_MARITAL) %>% summarise(FENT = sum(na.omit(FENT_NMU))/length(na.omit(FENT_NMU)), BUP = sum(na.omit(BUP_NMU))/length(na.omit(BUP_NMU)), METH = sum(na.omit(METH_NMU))/length(na.omit(METH_NMU)), MORPH = sum(na.omit(MORPH_NMU))/length(na.omit(MORPH_NMU)), OXY = sum(na.omit(OXY_NMU))/length(na.omit(OXY_NMU)), OXYM = sum(na.omit(OXYM_NMU))/length(na.omit(OXYM_NMU)), TRAM = sum(na.omit(TRAM_NMU))/length(na.omit(TRAM_NMU)), TAP = sum(na.omit(TAP_NMU))/length(na.omit(TAP_NMU)), COD = sum(na.omit(COD_NMU))/length(na.omit(COD_NMU)), COTC = sum(na.omit(COTC_NMU))/length(na.omit(COTC_NMU)), HYD = sum(na.omit(HYD_NMU))/length(na.omit(HYD_NMU)),HYDM = sum(na.omit(HYDM_NMU))/length(na.omit(HYDM_NMU)),SUF = sum(na.omit(SUF_NMU))/length(na.omit(SUF_NMU)),STIM = sum(na.omit(STIM_NMU))/length(na.omit(STIM_NMU)),BENZ = sum(na.omit(BENZ_NMU))/length(na.omit(BENZ_NMU)),THC = sum(na.omit(THC_NMU))/length(na.omit(THC_NMU)))
propmisuse_marital$FENT[is.na(propmisuse_marital$FENT)] <- 0
propmisuse_marital$BUP[is.na(propmisuse_marital$BUP)] <- 0
propmisuse_marital$METH[is.na(propmisuse_marital$METH)] <- 0
propmisuse_marital$MORPH[is.na(propmisuse_marital$MORPH)] <- 0
propmisuse_marital$OXY[is.na(propmisuse_marital$OXY)] <- 0
propmisuse_marital$OXYM[is.na(propmisuse_marital$OXYM)] <- 0
propmisuse_marital$TRAM[is.na(propmisuse_marital$TRAM)] <- 0
propmisuse_marital$TAP[is.na(propmisuse_marital$TAP)] <- 0
propmisuse_marital$COD[is.na(propmisuse_marital$COD)] <- 0
propmisuse_marital$COTC[is.na(propmisuse_marital$COTC)] <- 0
propmisuse_marital$HYD[is.na(propmisuse_marital$HYD)] <- 0
propmisuse_marital$HYDM[is.na(propmisuse_marital$HYDM)] <- 0
propmisuse_marital$SUF[is.na(propmisuse_marital$SUF)] <- 0
propmisuse_marital$STIM[is.na(propmisuse_marital$STIM)] <- 0
propmisuse_marital$BENZ[is.na(propmisuse_marital$BENZ)] <- 0
propmisuse_marital$THC[is.na(propmisuse_marital$THC)] <- 0
propmisuse_marital

rnames_marital <- propmisuse_marital$DEM_MARITAL         
mat_data_marital <- data.matrix(propmisuse_marital[,2:ncol(propmisuse_marital)]) 
rownames(mat_data_marital) <- rnames_marital

heatmaply(mat_data_marital,
          xlab = "Drugs",
          ylab = "Marital Status",
          main = "Drug misuse rates for each age by type of drugs",
          scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
    low = "steelblue", 
    high = "chocolate2", 
    midpoint = 0.5, 
    limits = c(0, 1)
  ))
```

```{r, include=FALSE}
propmisuse_marital <- dataca %>% group_by(DEM_MARITAL) %>% summarise(FENT = sum(na.omit(FENT_NMU))/length(na.omit(FENT_NMU)), BUP = sum(na.omit(BUP_NMU))/length(na.omit(BUP_NMU)), METH = sum(na.omit(METH_NMU))/length(na.omit(METH_NMU)), MORPH = sum(na.omit(MORPH_NMU))/length(na.omit(MORPH_NMU)), OXY = sum(na.omit(OXY_NMU))/length(na.omit(OXY_NMU)), OXYM = sum(na.omit(OXYM_NMU))/length(na.omit(OXYM_NMU)), TRAM = sum(na.omit(TRAM_NMU))/length(na.omit(TRAM_NMU)), TAP = sum(na.omit(TAP_NMU))/length(na.omit(TAP_NMU)), COD = sum(na.omit(COD_NMU))/length(na.omit(COD_NMU)), COTC = sum(na.omit(COTC_NMU))/length(na.omit(COTC_NMU)), HYD = sum(na.omit(HYD_NMU))/length(na.omit(HYD_NMU)),HYDM = sum(na.omit(HYDM_NMU))/length(na.omit(HYDM_NMU)),SUF = sum(na.omit(SUF_NMU))/length(na.omit(SUF_NMU)),STIM = sum(na.omit(STIM_NMU))/length(na.omit(STIM_NMU)),BENZ = sum(na.omit(BENZ_NMU))/length(na.omit(BENZ_NMU)),THC = sum(na.omit(THC_NMU))/length(na.omit(THC_NMU)))
propmisuse_marital$FENT[is.na(propmisuse_marital$FENT)] <- 0
propmisuse_marital$BUP[is.na(propmisuse_marital$BUP)] <- 0
propmisuse_marital$METH[is.na(propmisuse_marital$METH)] <- 0
propmisuse_marital$MORPH[is.na(propmisuse_marital$MORPH)] <- 0
propmisuse_marital$OXY[is.na(propmisuse_marital$OXY)] <- 0
propmisuse_marital$OXYM[is.na(propmisuse_marital$OXYM)] <- 0
propmisuse_marital$TRAM[is.na(propmisuse_marital$TRAM)] <- 0
propmisuse_marital$TAP[is.na(propmisuse_marital$TAP)] <- 0
propmisuse_marital$COD[is.na(propmisuse_marital$COD)] <- 0
propmisuse_marital$COTC[is.na(propmisuse_marital$COTC)] <- 0
propmisuse_marital$HYD[is.na(propmisuse_marital$HYD)] <- 0
propmisuse_marital$HYDM[is.na(propmisuse_marital$HYDM)] <- 0
propmisuse_marital$SUF[is.na(propmisuse_marital$SUF)] <- 0
propmisuse_marital$STIM[is.na(propmisuse_marital$STIM)] <- 0
propmisuse_marital$BENZ[is.na(propmisuse_marital$BENZ)] <- 0
propmisuse_marital$THC[is.na(propmisuse_marital$THC)] <- 0
propmisuse_marital

rnames_marital <- propmisuse_marital$DEM_MARITAL         
mat_data_marital <- data.matrix(propmisuse_marital[,2:ncol(propmisuse_marital)]) 
rownames(mat_data_marital) <- rnames_marital

mari <- heatmaply(mat_data_marital,
          xlab = "Drugs",
          ylab = "Marital Status",
          main = "Drug misuse rates for each age by type of drugs",
          scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
    low = "steelblue", 
    high = "chocolate2", 
    midpoint = 0.5, 
    limits = c(0, 1)
  ))
htmlwidgets::saveWidget(mari, "marital.html")

```

```{r}
par(mfrow=c(4,4))
hist((dataca %>% filter(FENT_NMU =="1"))$DEM_AGE10,main="FENT",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(BUP_NMU =="1"))$DEM_AGE10,main="BUP",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(METH_NMU =="1"))$DEM_AGE10,main="METH",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(MORPH_NMU =="1"))$DEM_AGE10,main="MORPH",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(OXY_NMU =="1"))$DEM_AGE10,main="OXY",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(OXYM_NMU =="1"))$DEM_AGE10,main="OXYM",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(TRAM_NMU =="1"))$DEM_AGE10,main="TRAM",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(TAP_NMU =="1"))$DEM_AGE10,main="TAP",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(COD_NMU =="1"))$DEM_AGE10,main="COD",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(COTC_NMU =="1"))$DEM_AGE10,main="COTC",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(HYD_NMU =="1"))$DEM_AGE10,main="HYD",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(HYDM_NMU =="1"))$DEM_AGE10,main="HYDM",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(SUF_NMU =="1"))$DEM_AGE10,main="SUF",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(STIM_NMU =="1"))$DEM_AGE10,main="STIM",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(BENZ_NMU =="1"))$DEM_AGE10,main="BENZ",xlab="Age",ylim=c(0,80))
hist((dataca %>% filter(THC_NMU =="1"))$DEM_AGE10,main="THC",xlab="Age",ylim=c(0,80))
```

```{r}
dataca$healthcpi
```


```{r}
datcpi <- dataca_totalmisuse %>% group_by(DEM_LOCATION) %>% summarise(cpi = mean(healthcpi), prop_misuse = sum(has_misuse)/n()) %>% filter(prop_misuse > 0.01)

ggplot(datcpi, aes(cpi, prop_misuse)) +
  geom_smooth(method="lm") +
  geom_point(size=3) +
  theme_bw() + 
  xlab("cpi") +
  ylab("proportion of people who have misused drugs") +
  ggtitle("Proportion of people who have misused drugs vs. CPI") + 
  expand_limits(y=0) 

```

```{r}
datcsi <- dataca_totalmisuse %>% group_by(DEM_LOCATION) %>% summarise(csi = mean(csi), prop_misuse = sum(has_misuse)/n()) %>% filter(prop_misuse > 0.01)

ggplot(datcsi, aes(csi, prop_misuse)) +
  geom_smooth(method="lm") +
  geom_point(size=3) +
  theme_bw() + 
  xlab("csi") +
  ylab("proportion of people who have misused drugs") +
  ggtitle("Proportion of people who have misused drugs vs. ") 

```

```{r}
dathealthcare_pctg <- dataca_totalmisuse %>% group_by(DEM_LOCATION) %>% summarise(healthcare_pctg = mean(healthcare_pctg), prop_misuse = sum(has_misuse)/n()) %>% filter(prop_misuse > 0.01)

ggplot(dathealthcare_pctg, aes(healthcare_pctg, prop_misuse, color = DEM_LOCATION, group = 1)) +
  geom_smooth(method="lm") +
  geom_point(size=3) +
  theme_bw() + 
  xlab("healthcare_pctg") +
  ylab("proportion of people who have misused drugs") +
  ggtitle("Proportion of people who have misused drugs vs healthcare_pctg") 

```




























